style: github
template: CHANGELOG.tpl.md
info:
  title: CHANGELOG
  repository_url: https://github.com/levirs565/kasten-note
options:
  commits:
    # filters:
    #   Type: []
  commit_groups:
    # title_maps: []
    group_by: Author.Name
  header:
    pattern: "^(.*)$"
    pattern_maps:
      - Subject
  notes:
    keywords:
      - BREAKING CHANGE
